name: Godot CI

on:
  push:
    branches: [ main ] # Thay 'main' bằng nhánh chính của bạn
  pull_request:
    branches: [ main ]

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1 # Docker image cho Godot 4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable

      - name: Build Web Export
        run: |
          godot --headless --export-release "Web" ./build/web/index.html
        env:
          GODOT_VERSION: 4.4.1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages # Nhánh để triển khai GitHub Pages
